[mirror]
name = docker_all
url = https://download.docker.com/linux/ubuntu/
dist = focal, jammy, noble, resolute
release = default
origin = default
label = default
arch = amd64, all
components = stable, edge
path = docker_all
