[mirror]
name = suricata-stable
url = http://ppa.launchpad.net/oisf/suricata-stable/ubuntu
dist = focal, jammy
release = default
components = main
arch = amd64
origin = default
label = default
path = suricata-stable
merge = yes
update = never